from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.orm import Session
from pydantic import BaseModel
import json
import os

from app.database.connection import get_db
from app.database.models import BuildingProfile, Anomaly, Recommendation, Recommendation as RecModel
from app.agents.pipeline import _llm_call, _get_api_key, _raw_llm_call

router = APIRouter()

class ChatRequest(BaseModel):
    session_id: str
    message: str

CHAT_SYSTEM_PROMPT = """
You are the SustainAI Multi-Agent Coordinator. You have access to the building profile, detected anomalies, and recommendations generated by the reasoning pipeline.

Your goal is to answer user questions about their energy sustainability plan with high precision.
Use the provided context to justify your answers. If you don't know something based on the data, say so.

CONTEXT:
{context}

Guidelines:
1. Be professional and data-driven.
2. If the user asks about a specific device, check if it's in the 'critical' list before suggesting changes.
3. Reference specific savings and anomaly patterns from the context.
"""

@router.post("/chat")
async def chat_with_agents(req: ChatRequest, db: Session = Depends(get_db)):
    # 1. Fetch Context
    profile = db.query(BuildingProfile).filter(BuildingProfile.session_id == req.session_id).first()
    if not profile:
        raise HTTPException(status_code=404, detail="Session not found")
        
    anomalies = db.query(Anomaly).filter(Anomaly.session_id == req.session_id).all()
    recommendations = db.query(RecModel).filter(RecModel.session_id == req.session_id).all()
    
    context_data = {
        "building_profile": {
            "type": profile.building_type,
            "name": profile.building_name,
            "critical_devices": profile.critical_devices,
            "constraints": profile.special_constraints
        },
        "detected_anomalies": [
            {"device": a.device, "reason": a.reason, "severity": a.severity} for a in anomalies[:10]
        ],
        "active_recommendations": [
            {"issue": r.issue, "recommendation": r.recommendation, "savings": r.estimated_monthly_loss} for r in recommendations
        ]
    }
    
    context_str = json.dumps(context_data, indent=2)
    system_prompt = CHAT_SYSTEM_PROMPT.format(context=context_str)
    
    # 2. Call LLM
    api_key = _get_api_key()
    if not api_key:
        return {"response": "I'm currently in offline mode. Based on your profile, I recommend following the generated roadmap. (API Key missing for live chat)"}
        
    try:
        response = _raw_llm_call(api_key, system_prompt, req.message)
        return {"response": response}
    except Exception as e:
        return {"response": f"I encountered an error conferring with the agents: {str(e)}"}
