from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.orm import Session
from pydantic import BaseModel
import json
import os

from app.database.connection import get_db
from app.database.models import AgentLog, BuildingProfile, Anomaly, DoctorAudit, Recommendation as RecModel, SessionReport
from app.agents.pipeline import get_active_node, _raw_llm_call

router = APIRouter()

class ChatRequest(BaseModel):
    session_id: str
    message: str

CHAT_SYSTEM_PROMPT = """
You are the SustainAI Multi-Agent Coordinator. You have access to the building profile, detected anomalies, and recommendations generated by the reasoning pipeline.

Your goal is to answer user questions about their energy sustainability plan with high precision.
Use the provided context to justify your answers. If you don't know something based on the data, say so.

CONTEXT:
{context}

Guidelines:
1. Be professional and data-driven.
2. If the user asks about a specific device, check if it's in the 'critical' list before suggesting changes.
3. Reference specific savings and anomaly patterns from the context.
"""

@router.post("/chat")
async def chat_with_agents(req: ChatRequest, db: Session = Depends(get_db)):
    # 1. Fetch Context
    profile = db.query(BuildingProfile).filter(BuildingProfile.session_id == req.session_id).first()
    if not profile:
        raise HTTPException(status_code=404, detail="Session not found")
        
    anomalies = db.query(Anomaly).filter(Anomaly.session_id == req.session_id).all()
    recommendations = db.query(RecModel).filter(RecModel.session_id == req.session_id).all()
    logs = (
        db.query(AgentLog)
        .filter(AgentLog.session_id == req.session_id)
        .order_by(AgentLog.created_at.desc())
        .limit(30)
        .all()
    )
    audits = (
        db.query(DoctorAudit)
        .filter(DoctorAudit.session_id == req.session_id)
        .order_by(DoctorAudit.created_at.desc())
        .limit(10)
        .all()
    )
    report = (
        db.query(SessionReport)
        .filter(SessionReport.session_id == req.session_id)
        .order_by(SessionReport.created_at.desc())
        .first()
    )
    
    context_data = {
        "building_profile": {
            "type": profile.building_type,
            "name": profile.building_name,
            "critical_devices": profile.critical_devices,
            "constraints": profile.special_constraints
        },
        "detected_anomalies": [
            {"device": a.device, "reason": a.reason, "severity": a.severity} for a in anomalies[:10]
        ],
        "active_recommendations": [
            {
                "issue": r.issue,
                "recommendation": r.recommendation,
                "savings": r.estimated_monthly_loss,
                "control_action": r.control_action,
                "reasoning_proof": r.reasoning_proof,
            } for r in recommendations
        ],
        "doctor_audits": [
            {"device": a.device, "status": a.verification_status, "notes": a.doctor_notes}
            for a in audits
        ],
        "recent_agent_logs": [
            {
                "agent": l.agent_name,
                "device": l.device,
                "action": l.action,
                "output": l.output,
                "timestamp": str(l.created_at),
            }
            for l in logs
        ],
        "active_node": get_active_node(req.session_id),
        "latest_report": report.final_explanation if report else "",
    }
    
    context_str = json.dumps(context_data, indent=2)
    system_prompt = CHAT_SYSTEM_PROMPT.format(context=context_str)
    
    # 2. Call LLM — try all available providers
    import os
    providers = []
    groq_key = os.getenv("GROQ_API_KEY")
    nvidia_key = os.getenv("NVIDIA_API_KEY")
    if groq_key and groq_key != "your_key_here":
        providers.append(("groq", groq_key))
    if nvidia_key and nvidia_key != "your_key_here":
        providers.append(("nvidia", nvidia_key))
    
    def local_response(reason: str):
        msg = req.message.lower()
        agent_filter = None
        for label in ["doctor", "anomaly", "context", "research", "recommendation", "surveillance", "explanation"]:
            if label in msg:
                agent_filter = label
                break

        selected_logs = logs
        if agent_filter:
            selected_logs = [l for l in logs if l.agent_name and agent_filter in l.agent_name.lower()]

        lines = [
            reason,
            f"Current active node: {get_active_node(req.session_id)}.",
        ]
        lines.append(
            f"Latest {agent_filter.title()} Agent context:"
            if agent_filter else
            "Latest coordination context:"
        )

        if selected_logs:
            for log in selected_logs[:5]:
                lines.append(f"- {log.agent_name}: {log.action} -> {log.output}")
        else:
            lines.append("- No matching agent logs are available yet.")

        if audits and ("doctor" in msg or "fix" in msg or "verify" in msg):
            lines.append("Doctor audit evidence:")
            for audit in audits[:5]:
                lines.append(f"- {audit.device}: {audit.verification_status}. {audit.doctor_notes}")

        if report and ("explain" in msg or "report" in msg or "summary" in msg):
            lines.append("Latest explanation excerpt:")
            lines.append(report.final_explanation[:1200])

        return {"response": "\n".join(lines)}

    if not providers:
        return local_response("Live chat is in offline mode because no GROQ_API_KEY or NVIDIA_API_KEY is configured.")
    
    provider_errors = []
    for provider_info in providers:
        try:
            response = _raw_llm_call(provider_info, system_prompt, req.message)
            return {"response": response}
        except Exception as e:
            provider_errors.append(f"{provider_info[0]}: {type(e).__name__} - {e}")
            continue
    
    return local_response("Live AI provider calls failed. " + " | ".join(provider_errors[:2]))
